### ISSUE TITLE
Fatal error: Cannot read property 'distribute' of undefined

### ISSUE THREAD

**Issue by soultech67** [jkphl/svg-sprite#94]
We're running into a new error after updating recently to the newest version of svg-sprite. For us, the task is fired off during a grunt build, using grunt-svg-sprite module. 

The options grunt-svg-sprite use look like this (I added the log verbose to get the dump, normally we don't have a log statement)
```javascript
'use strict';

module.exports = function (grunt) {
  // Create SVG sprite
  // see: https://github.com/jkphl/grunt-svg-sprite
  grunt.config.set('svg_sprite', {
    app: {
      cwd: '<%= paths.src.app.media %>/',
      src: ['**/*.svg'],
      dest: '<%= paths.dist.media %>/app/',
      options: {
        log: 'verbose',
        mode: {
          inline: true,
          symbol: {
            dest: './sprites',
            sprite: 'icons.svg'
          }
        }
      }
    }
  });
};
```

The error message I'm getting is:
```
Running "svg_sprite:app" (svg_sprite) task
2015-05-11 14:26:31 - verbose: Initialized spriter configuration
2015-05-11 14:26:31 - info: Created spriter instance
2015-05-11 14:26:31 - verbose: Added shape "icons:regular"
2015-05-11 14:26:31 - verbose: Added shape "scott:regular"
2015-05-11 14:26:31 - error: Optimizing "scott.svg" with SVGO failed with error "%s" ArgumentError: Invalid SVG file
    at Object.SVGShape._initSVG (/Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/lib/svg-sprite/shape.js:317:14)
    at Object.SVGShape.setSVG (/Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/lib/svg-sprite/shape.js:304:14)
    at /Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/lib/svg-sprite/transform/svgo.js:68:10
    at optimizeOnceCallback (/Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/node_modules/svgo/lib/svgo.js:43:17)
    at /Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/node_modules/svgo/lib/svgo.js:65:9
    at Object.sax.onend (/Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/node_modules/svgo/lib/svgo/svg2js.js:140:26)
    at emit (/Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/node_modules/svgo/node_modules/sax/lib/sax.js:625:33)
    at end (/Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/node_modules/svgo/node_modules/sax/lib/sax.js:667:3)
    at Object.write (/Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/node_modules/svgo/node_modules/sax/lib/sax.js:929:30)
    at Object.SAXParser.close (/Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/node_modules/svgo/node_modules/sax/lib/sax.js:153:38)
2015-05-11 14:26:31 - verbose: Added shape "slider-nav:regular"
Fatal error: Cannot read property 'distribute' of undefined
```

I tracked it down to the regex in shape.js line 317 in v 1.2.3 - looks like the validation was added 4/18 (changeset: https://github.com/jkphl/svg-sprite/commit/0a921c6ea26aeda2355381f349b79b5c9f2db3de)

Here's an SVG file that repros the issue: 
* if you comment out the first line (as it is below) - (the rect declaration) the grunt build fails with the above noted error.
* If you uncomment the first line (the rect declaration) the grunt build succeeds.

```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
  <!-- <rect x="25" y="25" width="200" height="200" fill="lime" stroke-width="4" stroke="pink" /> -->

  <symbol id="calendar" viewBox="0 0 60 60">
    <path d="M47.19 12.54h-0.4V8.72c0-2.05-1.67-3.72-3.72-3.72 -2.05 0-3.72 1.67-3.72 3.72v3.82h-5.61V8.72C33.74 6.67 32.07 5 30.02 5c-2.05 0-3.72 1.67-3.72 3.72v3.82h-5.61V8.72c0-2.05-1.67-3.72-3.72-3.72 -2.05 0-3.72 1.67-3.72 3.72v3.82h-0.43c-3.84 0-6.97 3.13-6.97 6.97v28.54c0 3.84 3.13 6.96 6.97 6.96h34.37c3.84 0 6.96-3.12 6.96-6.96V19.5C54.15 15.66 51.03 12.54 47.19 12.54zM41.44 8.72c0-0.9 0.73-1.63 1.63-1.63 0.9 0 1.63 0.73 1.63 1.63v3.82 1.04 3.9c0 0.9-0.73 1.63-1.63 1.63 -0.9 0-1.63-0.73-1.63-1.63v-3.89 -1.04V8.72zM28.39 8.72c0-0.9 0.73-1.63 1.63-1.63s1.63 0.73 1.63 1.63v3.82 1.04 3.9c0 0.9-0.73 1.63-1.63 1.63s-1.63-0.73-1.63-1.63v-3.89 -1.04V8.72zM15.34 8.72c0-0.9 0.73-1.63 1.63-1.63 0.9 0 1.63 0.73 1.63 1.63v3.82 1.04 3.9c0 0.9-0.73 1.63-1.63 1.63 -0.9 0-1.63-0.73-1.63-1.63v-3.89 -1.04V8.72zM12.82 14.63h0.43v2.85c0 2.05 1.67 3.72 3.72 3.72 2.05 0 3.72-1.67 3.72-3.72v-2.85h5.61v2.85c0 2.05 1.67 3.72 3.72 3.72 2.05 0 3.72-1.67 3.72-3.72v-2.85h5.61v2.85c0 2.05 1.67 3.72 3.72 3.72 2.05 0 3.72-1.67 3.72-3.72v-2.85h0.4c2.69 0 4.87 2.19 4.87 4.87v6.1H7.94v-6.09C7.94 16.81 10.13 14.63 12.82 14.63zM47.19 52.91H12.82c-2.69 0-4.88-2.19-4.88-4.88V27.69h44.12v20.35C52.06 50.73 49.87 52.91 47.19 52.91zM13.28 48.21h33.8V31.32H13.28V48.21zM15.37 40.97h4.43v5.15h-4.43V40.97zM34.42 40.97h4.18v5.15h-4.18V40.97zM32.33 46.13h-4.18v-5.15h4.18V46.13zM34.42 38.88v-5.47h4.18v5.48H34.42zM32.33 38.88h-4.18v-5.47h4.18V38.88zM26.06 38.88h-4.17v-5.47h4.18V38.88zM26.06 40.97v5.15h-4.17v-5.15H26.06zM40.68 46.13v-5.15h4.3v5.15H40.68L40.68 46.13zM44.98 38.88h-4.3v-5.47h4.3V38.88zM19.8 33.41v5.48h-4.43v-5.47H19.8z" />
  </symbol>
</svg>
```

**Comment by jkphl** [comment]
Could you please check which version of SVGO you are running? There has been [a similar issue](https://github.com/jkphl/svg-sprite/issues/82) before, which was caused by an SVGO bug. I'd like to ensure that this is not the problem before we dig deeper.

**Comment by soultech67** [comment]
```
/Users/sburkh4/Projects/SHS/shs-web/node_modules/grunt-svg-sprite/node_modules/svg-sprite/node_modules/svgo/bin/svgo -v
0.5.2
```

**Comment by jkphl** [comment]
Hmm, ok, so it's the most recent one. I'll try to reproduce the case tomorrow and get back to you.

**Comment by soultech67** [comment]
I was able to bypass the bug by modifying shape.js line 317 to change the regex to /.*/ ;) - not the fix you're looking for though I'd guess. Seems like it's related to the regex though.

**Comment by jkphl** [comment]
That's a valuable hint, thanks a lot. I made a little change to the regex a couple of days ago, maybe that introduced a regression of some kind. I'll look into it. Thanks again!

**Comment by soultech67** [comment]
One more hint then, I tried the regex you originally committed on 4/18 but that didn't fix this issue. Thanks for being so responsive!

**Comment by jkphl** [comment]
You're welcome. Thanks again!

**Comment by jkphl** [comment]
That was a weird one indeed, and I didn't really understand it (although it should be fixed now). It seems that SVGO under certain circumstances calls its result handler twice: Once with the regular optimized SVG, and once with an empty `<svg/>` element, which doesn't match the regex, hence the error. I'll further investigate why this double call is happening. In the meantime, I modified the regex to suit all situations.

**Comment by linnett** [comment]
I am currently experiencing this error using it with a normal npm script. 
Node version 0.12.7

**Comment by jkphl** [comment]
Could you please post more details, like your complete config and the SVG files used?

**Comment by linnett** [comment]
Thanks for the speedy reply! Code is exactly from the example: 

  ```javascipt
  var spriter = new SVGSpriter({
        dest: global.DIST + '/images/svgs',
        mode: {
            css: {
                render: {
                    css:true
                }
            }
        }
    }),
    cwd = path.resolve(global.SRC + '/images/svgs');

    glob.glob('**/*.svg', {cwd: cwd}, function(err, files) {
        files.forEach(function(file){

            spriter.add(new File({
                path: path.join(cwd, file),
                base: cwd,
                contents: fs.readFileSync(path.join(cwd, file))
            }));
        })

        spriter.compile(function(error, result, data){
            for (var type in result.css) {
                mkdirp.sync(path.dirname(result.css[type].path));
                fs.writeFileSync(result.css[type].path, result.css[type].contents);
            }
        });
    });
   ```
The version of svg-sprite is: 1.2.12.
Is there anything specific you need to know?

**Comment by jkphl** [comment]
Could you please try activating the debug logs and see if there's an explanation?

```js
{
	dest: global.DIST + '/images/svgs',
	log: 'debug',
	// ...
}

**Comment by linnett** [comment]
Hi - I tried it again this morning and it appears to be working, oddly! I'm wondering if the error was caused by a corrupt SVG or something like that? Thanks for the assistance anyway!

**Comment by jkphl** [comment]
Oh great! Sorry for me not being more responsive, I'm at a conference right now. But checking your SVGs would've probably been the next thing I had suggested. q:)

**Comment by linnett** [comment]
You've extremely responsive and helpful :). Thank you

**Comment by jarcoal** [comment]
Just encountered this issue, however I did not update my version of svg-sprite.  However I did upgrade to node 5.X, so that could be related.

**Comment by jkphl** [comment]
@jarcoal We are using *svg-sprite* with Node 5 in production without any issues, so this shouldn't be the problem. Again, could you please post your complete configuration (and double-check that all of your SVG files are valid; you might also try it with SVGO optimization disabled)? Thanks!

**Comment by jarcoal** [comment]
Thanks for the quick reply!  I'm using svg-sprite through grunt-svg-sprite, and only noticed this issue on our CI server at first.  I tried to duplicate it locally but could not.  Then I cleared out my node_nodules and re-installed them, that's when I started getting the error locally as well.

Here is my grunt config:

```json
    svg_sprite: {
      sm: {
        expand: true,
        cwd: 'src/svg',
        src: ['*.svg'],
        dest: 'dist',
        options: {
          shape: {
            dimension: {
              maxWidth: 16,
              maxHeight: 16
            },
          },
          mode: {
            css: {
              dimensions: "",
              sprite: 'sm.svg',
              prefix: ".svg-%s-sm",
              bust: false,
              render: {
                css: {
                  dest: 'svg-sm.css'
                }
              }
            },
          }
        }
      },
      md: {
        expand: true,
        cwd: 'src/svg',
        src: ['*.svg'],
        dest: 'dist',
        options: {
          shape: {
            dimension: {
              maxWidth: 24,
              maxHeight: 24
            },
          },
          mode: {
            css: {
              dimensions: "",
              sprite: 'md.svg',
              prefix: ".svg-%s-md",
              bust: false,
              render: {
                css: {
                  dest: 'svg-md.css'
                }
              }
            },
          }
        }
      },
      lg: {
        expand: true,
        cwd: 'src/svg',
        src: ['*.svg'],
        dest: 'dist',
        options: {
          shape: {
            dimension: {
              maxWidth: 32,
              maxHeight: 32
            },
          },
          mode: {
            css: {
              dimensions: "",
              sprite: 'lg.svg',
              prefix: ".svg-%s-lg",
              bust: false,
              render: {
                css: {
                  dest: 'svg-lg.css'
                }
              }
            },
          }
        }
      }
    },
```

And here is the line I have in my package.json:

```json
  "devDependencies": {
    "grunt-svg-sprite": "^1.0.18",
    // ...
  }
```

**Comment by jkphl** [comment]
@jarcoal I see. Is there anything holding you back from updating *grunt-svg-sprite* to the most recent version (1.2.14)?

**Comment by jarcoal** [comment]
Nope, but I tried that and it didn't make a difference.

**Comment by jkphl** [comment]
@jarcoal There has been a regex issue that should've been fixed with version 1.2.4 (see above), so I'd definitely recommend updating to the most recent version anyway. Also, did you try to disable SVGO for a moment?

**Comment by jarcoal** [comment]
Ok I upgraded to 1.2.14, cleared out `node_modules` and re-installed.  Still getting the same error, however I did bump up the log level and now see an SVGO error:

```
2015-10-23 13:57:40 - verbose: Added shape "ios-calendar-outline:regular"
2015-10-23 13:57:40 - error: Optimizing "ios-calendar-outline.svg" with SVGO failed with error "TypeError: Cannot read property 'length' of undefined"
Fatal error: Cannot read property 'distribute' of undefined
```

I'm not sure how to disable SVGO.

**Comment by jkphl** [comment]
@jarcoal Ah, that's what I thought. Disabling SVGO is simple:

```js
var config = {
	shape: {
		transform: []
	}
}
```

This will skip SVGO, but leave your SVG files unoptimized, which isn't ideal of course. You could further dig into it and disable single SVGO plugins instead of the whole optimization, but I'd recommend [using the online configurator](http://jkphl.github.io/svg-sprite) then. In any case, if SVGO is the problem, then there's nothing I could do from the perspective of *svg-sprite*.

**Comment by jarcoal** [comment]
That looks to be the case.  I wonder if [0.6.1 release](https://github.com/svg/svgo/releases/tag/v0.6.1) of svgo that they cut two days ago fixes this.

**Comment by jkphl** [comment]
Well, bumping the SVGO dependency in *svg-sprite*'s `package.json` and updating your modules will tell you. If so, I'd happily push out an updated release for you.

**Comment by jarcoal** [comment]
Disabling SVGO fixed the issue, so that's settled.  0.6.1 yielded the same error, so looks like we're stuck waiting on a fix on their end.

Thanks for your help @jkphl .  Much appreciated.  I will let you know if I make any further progress on resolving this.

**Comment by jkphl** [comment]
You're very welcome. Maybe you could take the time and file an issue at SVGO's end, providing your offending SVG as an example‽ Also, please consider digging into SVGO's plugin configuration as disabling a single one of them could well solve your problem. There are some rather aggressive plugins that tend to make trouble with particular SVGs. Good luck (and happy spriting)!
